### ISSUE TITLE
Peak pattern occurrences 

### ISSUE THREAD

**Issue by brunoerg** [allarddenis/time-series-pattern-recognition#1]
What function can return me the peak pattern occurences? 

Like your example, with the data = [4,4,2,2,3,5,5,6,3,1,1,2,2,2,2,2,2,1] the peak pattern occurences are: <<=<>> & <=====>

But, what function can I input my pattern and return the peak pattern occurences? 

Tks guys!

**Comment by allarddenis** [comment]
Hi,

Look at **v1 branch** & in **/src**, run the following (as mentioned in related readme) : 

> python tests.py

You should find what you're looking for.

The master branch of the repo is no longer meant to do such operation as finding a particular pattern's occurrences in a series.

I hope that helps !

**Comment by allarddenis** [comment]
Answered.

**Comment by brunoerg** [comment]
Thanks!
